apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: capstone-frontend-$COLOR
  name: capstone-frontend-$COLOR
spec:
  replicas: 2
  selector:
    matchLabels:
      service: capstone-frontend
  template:
    metadata:
      labels:
        service: capstone-frontend-$COLOR
    spec:
      containers:
        - image: duyhuynhdn/capstone-frontend:latest
          name: capstone-frontend
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      restartPolicy: Always