apiVersion: v1
kind: Service
metadata:
  name: capstone-frontend
  labels:
    run: capstone-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: capstone-frontend